# Generated by Django 5.2.16 on 2026-07-21 16:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('profiles', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_moderation', 'Pending moderation'), ('published', 'Published'), ('changes_requested', 'Changes requested'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=32)),
                ('slug', models.SlugField(max_length=160)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('team_formation', 'Team formation'), ('prototype', 'Prototype'), ('pilot', 'Pilot'), ('active', 'Active'), ('completed', 'Completed')], default='idea', max_length=32)),
                ('problem_statement', models.TextField(blank=True)),
                ('goal_statement', models.TextField(blank=True)),
                ('expected_outcome', models.TextField(blank=True)),
                ('timeline_text', models.CharField(blank=True, max_length=500)),
                ('scope', models.CharField(choices=[('local', 'Local'), ('national', 'National'), ('international', 'International')], default='local', max_length=16)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='taxonomy.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='taxonomy.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='taxonomy.country')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_moderated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='organizations.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('work_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='taxonomy.workformat')),
                ('working_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='taxonomy.language')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('role_label', models.CharField(blank=True, max_length=160)),
                ('is_public', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectFocus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_focuses', to='taxonomy.focusarea')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focuses', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('first_responsibility', models.CharField(blank=True, max_length=500)),
                ('commitment_hours_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats_total', models.PositiveSmallIntegerField(default=1)),
                ('seats_filled', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paused', 'Paused'), ('filled', 'Filled'), ('closed', 'Closed')], default='open', max_length=16)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('membership_role', models.CharField(choices=[('owner', 'Owner'), ('lead', 'Lead'), ('contributor', 'Contributor'), ('advisor', 'Advisor')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('removed', 'Removed')], default='active', max_length=16)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to='profiles.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('project_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='projects.projectrole')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('importance', models.CharField(choices=[('nice_to_have', 'Nice to have'), ('required', 'Required')], max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='projects.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_skills', to='taxonomy.skill')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'published_at'], name='projects_status_published_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'stage'], name='projects_category_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['application_deadline'], name='projects_deadline_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='projects_unique_active_slug'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='projects_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('application_deadline__isnull', True), ('starts_on__isnull', True), ('application_deadline__lte', models.F('starts_on')), _connector='OR'), name='projects_deadline_not_after_start'),
        ),
        migrations.AddConstraint(
            model_name='projectfocus',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'focus_area'), name='projects_unique_active_focus'),
        ),
        migrations.AddIndex(
            model_name='projectrole',
            index=models.Index(fields=['project', 'status'], name='projects_pr_project_dbc0c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectrole',
            constraint=models.CheckConstraint(condition=models.Q(('seats_total__gte', 1), ('seats_filled__gte', 0), ('seats_filled__lte', models.F('seats_total'))), name='projects_role_valid_seat_counts'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'active')), fields=('project', 'profile'), name='projects_unique_active_member'),
        ),
        migrations.AddConstraint(
            model_name='projectskill',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'skill'), name='projects_unique_active_skill'),
        ),
    ]
