# Generated by Django 5.2.16 on 2026-07-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('taxonomy', '0002_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='search_text',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='search_translit',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
