# Generated by Django 5.2.16 on 2026-07-21 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_moderation', 'Pending moderation'), ('published', 'Published'), ('changes_requested', 'Changes requested'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='draft', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_note', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=160)),
                ('display_name', models.CharField(max_length=160)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('members', 'Members'), ('public', 'Public')], default='private', max_length=16)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('unavailable', 'Unavailable')], default='unavailable', max_length=16)),
                ('availability_note', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_avatars', to='media.mediaasset')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='taxonomy.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='taxonomy.country')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_moderated', to=settings.AUTH_USER_MODEL)),
                ('remote_preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='taxonomy.workformat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('institution_name', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_educations', to='taxonomy.educationlevel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='profiles.profile')),
            ],
            options={
                'ordering': ('sort_order', '-started_on'),
            },
        ),
        migrations.CreateModel(
            name='ProfileExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.profile')),
                ('work_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_experiences', to='taxonomy.workformat')),
            ],
            options={
                'ordering': ('sort_order', '-started_on'),
            },
        ),
        migrations.CreateModel(
            name='ProfileLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('proficiency', models.CharField(choices=[('native', 'Native'), ('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('c2', 'C2')], max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_languages', to='taxonomy.language')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='profiles.profile')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('website', 'Website'), ('linkedin', 'LinkedIn'), ('portfolio', 'Portfolio'), ('github', 'GitHub'), ('other', 'Other')], max_length=16)),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='profiles.profile')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProfileProjectPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_preferences', to='taxonomy.category')),
                ('focus_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_preferences', to='taxonomy.focusarea')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_preferences', to='profiles.profile')),
                ('work_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_preferences', to='taxonomy.workformat')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_skills', to='taxonomy.skill')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['status', 'published_at'], name='profiles_status_published_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['visibility'], name='profiles_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country', 'city'], name='profiles_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='profiles_unique_active_slug'),
        ),
        migrations.AddConstraint(
            model_name='profileeducation',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('started_on')), _connector='OR'), name='profiles_education_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='profileexperience',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('ended_on__isnull', True), _connector='OR'), name='profiles_current_experience_has_no_end_date'),
        ),
        migrations.AddConstraint(
            model_name='profileexperience',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('started_on')), _connector='OR'), name='profiles_experience_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='profilelanguage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('profile', 'language'), name='profiles_unique_active_profile_language'),
        ),
        migrations.AddConstraint(
            model_name='profilelanguage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_primary', True)), fields=('profile',), name='profiles_one_primary_language'),
        ),
        migrations.AddConstraint(
            model_name='profileprojectpreference',
            constraint=models.CheckConstraint(condition=models.Q(('category__isnull', False), ('focus_area__isnull', False), ('work_format__isnull', False), _connector='OR'), name='profiles_preference_has_a_target'),
        ),
        migrations.AddConstraint(
            model_name='profileskill',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('profile', 'skill'), name='profiles_unique_active_profile_skill'),
        ),
        migrations.AddConstraint(
            model_name='profileskill',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_primary', True)), fields=('profile',), name='profiles_one_primary_skill'),
        ),
    ]
