# Generated by Django 5.2.16 on 2026-09-01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_externalidentity_userrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalAcceptance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document", models.CharField(choices=[("terms", "User terms"), ("personal_data", "Personal data consent"), ("age_confirmation", "Age confirmation"), ("public_profile", "Public profile distribution consent")], max_length=32)),
                ("version", models.CharField(max_length=32)),
                ("source", models.CharField(default="web", max_length=32)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="legal_acceptances", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["user", "document", "version"], name="users_legal_user_id_6d7b49_idx")],
                "constraints": [models.UniqueConstraint(condition=models.Q(("withdrawn_at__isnull", True)), fields=("user", "document"), name="users_unique_active_legal_acceptance")],
            },
        ),
    ]
