# Generated by Django 5.2.16 on 2026-07-24 08:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=32)),
                ('reason_code', models.CharField(default='publication_review', max_length=64)),
                ('decision_note', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderation_cases', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_moderation_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('opened_at',),
                'indexes': [models.Index(fields=['status', 'opened_at'], name='moderation__status_47d886_idx'), models.Index(fields=['content_type', 'object_id'], name='moderation__content_7c5992_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'in_review'))), fields=('content_type', 'object_id'), name='moderation_one_active_case_per_target')],
            },
        ),
    ]
