# Generated by Django 5.2.16 on 2026-07-21 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='project_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='projects.projectrole'),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_project_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projectapplication',
            index=models.Index(fields=['project_role', 'status'], name='application_project_7fa28a_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ('submitted', 'in_review', 'shortlisted', 'accepted'))), fields=('project_role', 'applicant'), name='applications_unique_active_role_application'),
        ),
    ]
