# Generated by Django 5.2.16 on 2026-07-21 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=127)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('quarantined', 'Quarantined'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=16)),
                ('scan_result', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_media_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('purpose', models.CharField(choices=[('avatar', 'Avatar'), ('logo', 'Logo'), ('project_cover', 'Project cover'), ('document', 'Document'), ('credential', 'Credential')], max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='media.mediaasset')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['uploaded_by', 'status'], name='media_media_uploade_aaf360_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['content_type', 'object_id', 'purpose'], name='media_media_content_d7c8c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaattachment',
            constraint=models.UniqueConstraint(fields=('asset', 'content_type', 'object_id', 'purpose'), name='media_unique_attachment_purpose'),
        ),
    ]
