# Generated by Django 5.2.16 on 2026-07-24

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="client_message_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.UniqueConstraint(
                condition=Q(("client_message_id__isnull", False), ("deleted_at__isnull", True)),
                fields=("conversation", "sender", "client_message_id"),
                name="chat_unique_active_client_message",
            ),
        ),
    ]
