# Generated by Django 5.2.16 on 2026-07-28

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatmessage_client_message_id"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("direct", "Direct"),
                    ("organization", "Organization"),
                    ("group", "Group"),
                ],
                default="direct",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_chat_messages",
                to="organizations.organization",
            ),
        ),
        migrations.CreateModel(
            name="ConversationOrganization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(default=timezone.now)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_participants",
                        to="chat.conversation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_participations",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="conversationorganization",
            index=models.Index(
                fields=["organization", "deleted_at"],
                name="chat_participant_org_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationorganization",
            constraint=models.UniqueConstraint(
                condition=Q(("deleted_at__isnull", True)),
                fields=("conversation", "organization"),
                name="chat_unique_active_organization",
            ),
        ),
    ]
