# Generated by Django 5.2.16 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_conversation_kinds_and_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationparticipant",
            name="is_direct",
            field=models.BooleanField(
                default=True,
                help_text="Visible participant; false for organization-member read state.",
            ),
        ),
    ]
